---
title: 'Test #2'
author: Rob Squire
output: pdf_document
---

###6.11
Let $H$ be a subgroup of a group $G$ and suppose that $g_{1},g_{2}\epsilon G$. Prove that the following conditions are equivalent.

##(a)
$g_{1}H = g_{2}H$

$Proof$
Let $g_{1}H = g_{2}H$.
Since $H$ is a subgroup of $G$, we know $e \epsilon H$.
Therefore, $g_{1}= g_{1}e \epsilon g_{1}H = g_{2}H$.
Similarly, $g_{2}= g_{2}e \epsilon g_{2}H = g_{1}H$.

Then since $H \leqq G$ $\exists$ inverses.
So $g_{1} \epsilon g_{2}H$ $\exists h \epsilon H$ such that $g_{1}=g_{2}h$ and $h^{-1}  \epsilon H$.

So $g_{1}^{-1}=g_{2}^{-1}h^{-1}$ and by similar argument $g_{2}^{-1}=g_{1}^{-1}h^{-1}$.
Thus $g_{1}H = g_{2}H$.


##(b)
$Hg_{1}^{-1}=Hg_{2}^{-1}$

$Proof$

Let $g_{1}^{-1}H = g_{2}^{-1}H$
Since $H$ is a subgroup of $G$, we know $e \epsilon H$.
Therefore, $g_{1}^{-1}= eg_{1}^{-1} \epsilon Hg_{1}^{-1} = Hg_{2}^{-1}$ and similarly $g_{2}^{-1}= eg_{2}^{-1} \epsilon Hg_{2}^{-1} = Hg_{1}^{-1}$.
So, $\exists h^{-1} \epsilon H$ such that $g_{1}^{-1}=h^{-1}g_{2}^{-1}$.
Then $g_{1}=g_{2}h$.
Recall that $H$ is a subgroup so $hH$ will equal $H$.
Thus $g_{1}H=g_{2}hH=g_{2}H$.
Therfore $g_{1}H \subseteq g_{2}H$


##(c)
$g_{1}H \subset g_{2}H$

$Proof$

Let $g_{1}H \subset g_{2}H$,
By Theorem 6.4 (Judson)
As any two left coests of a subgroup $H$ are either disjoint or equal.
Thus $g_{1}H \subset g_{2}H$ implies that  $g_{1}H=g_{2}H$.
Since $e \epsilon H$, $g_{2}=g_{2}H =g_{1}H$
Thus $g_{2} \epsilon g_{1}H$

##(d)
$g_{2} \epsilon g_{1}H$

$Proof$

Let  $g_{1}^{-1}g_{2} \epsilon H$.
So $\exists h \epsilon H$, such that $g_{2}=g_{1}h$.
Then $g_{2}^{-1}=h^{-1}g_{1}^{-1}$.
Then $g_{2}^{-1}g_{2}=h^{-1}g_{1}^{-1}g_{2}$.
 $e=h^{-1}g_{1}^{-1}g_{2}$.
 $he=hh^{-1}g_{1}^{-1}g_{2}$.
 $h=g_{1}^{-1}g_{2}$.
So, $g_{1}^{-1}g_{2} \epsilon H$

##(e)
$g_{1}^{-1}g_{2} \epsilon H$

$Proof$
Let $g_{1}^{-1}g_{2} \epsilon H$.
So, $\exists h \epsilon H$ such that $g_{1}^{-1}g_{2} \epsilon h$.
Thus $g_{2}=g_{1}h$.
Thus $g_{2}H=(g_{1}h)H =g_{1}(hH)=g_{1}H$
$\square$


###6.12
If $ghg^{-1} \epsilon H$ $\forall$  $g \epsilon G$ and $h \epsilon H$, show that right coests are identical to left cosets.  That is, show that $gH=Hg \forall g \epsilon G$.


$Proof$
Let $ghg^{-1} \epsilon H$ $\forall$  $g \epsilon G$ and $h \epsilon H$.
Since $h \epsilon H$, then $h$ can be anything in $H$, so $h=H$.
So $ghg^{-1} \epsilon H = gHg^{-1} \subseteq H$ $\forall$ $g \epsilon G$ and $h \epsilon H$.
Consider $g^{-1}\epsilon G$.
So, $g^{-1}H(g^{-1})^{-1} \subseteq H = g^{-1}Hg \subseteq H$ $\forall g \epsilon G$.
Since $g^{-1}Hg \subseteq H$. 
Then $g(g^{-1}Hg)g^{-1} \subseteq gHg^{-1}$.
Thus $H \subseteq gHg^{-1}$.

So, $ghg^{-1} \subseteq H$ and $H \subseteq g^{-1}hg$.
Then $gHg^{-1}g \subseteq Hg = gH \subseteq Hg$ and $gH \subseteq gg^{-1}H= gH \subseteq Hg$.
Thus $gH=Hg$ and right cosets are equal to left cosets.
$\square$

###9.5
Show $U(5)$ is isomorphic to $U(10)$, but $U(12)$ is not.

$Proof$
Consider $U(5)={1,2,3,4}$,
         $U(10)={1,3,7,9}$,
         $U(12)={1,5,7,11}$.

In order for two groups to be isomorphic the order of each element in a group must correspond to a the order of an element in the other group.  

Furthermore by Theorem 9.6 (iv), if an isomorphism exists between a two groups G & H,then if G is cyclic, then H is cyclic.

$U(5)$, $U(10)$, and $U(12)$, all contain the same number of elements which is a necessary condition for isomorphism between groups.

Consider, $U(5)$ is cyclic under the generator {2} and thus has order 4.  $U(10)$ is also cyclic under the generator {3} and also has order 4.  $U(12)$ is not cyclic so there exists no element in $U(12)$ with order 4.  Therefore $U(12)$ cannot be isomorphic to $U(5)$ or $U(10)$.
$\square$
### 9.25
Prove or disprove: There is a noncyclic abelian group of order 52.

$Proof$
Consider the direct product of two groups $G_{26}$ and $G_{2}$.  
Then the direct product of $G_{26}$ which is $G_{13}$ and $G_{2}$.
So, we have $G_{13}$x$G_{2}$x$G_{2}$ or $G_{13}$x$G_{4}$
Consider since $G_{13}$ is of prime order then it must be cyclic but $G_{4}$ does not necessarily have to be cyclic.  
Consider $U(12)$ from the previous question, has order 4 but is non-cyclic.  
Since the product of a cyclic group $G_{13}$ and non cyclic group $G_{4}$ result in a group of order 52 and they are abelian since both $G_{13}$x$G_{4}$ and $G_{4}$x$G_{13}$ result $G_{52}$, there exists a noncyclic abelian group of order 52.
$\square$

### 9.27
Let $G \cong H$. Show that if $G$ is cyclic, then so is $H$.

$Proof$
If $G$ is isomorphic to $H$, then if $G$ is cyclic, $H$ is cyclic.
Let $G$ be isomorphic to $H$ and $G$ be cyclic.
Then $G$ and $H$ have the same number of elements, say $n$ and each element of the respective groups has the same order.
Since $G_{n}$ is cyclic, $\exists$ a generator $<g>$ that produces every element in $G$ and is of order $n$ by definition of cyclic. 
Since $H$ is isomorphic then it must have $n$ elements, hence $H_{n}$.
Then an isomorphism requires each element of $G$ to have a corresponding element in $H$ so by definition of isomorphic there must exist an element that also has order $n$. 
Thus $\exists$ a generator of $H$.  

Since there exists an element in $H$ that genereates $H$, $H$ is cyclic.
$\square$

###10.11

If a group $G$ has exactly one subgroup $H$ of order $k$, prove that $H$ is normal in $G$.

$Proof$
Suppose group $G$ has exactly one subgroup $H$ of order $k$.
Let $g_{1}H$ and $g_{2}H$ be two cosets of the $H$ in $G$.  
Since $H$ is the only subgroup we know that $g_{1}H=g_{2}H$
